### ISSUE TITLE
Gem not published

### ISSUE THREAD

**Issue by dnd** [lostisland/faraday-http#11]
The README indicates to install the gem named `faraday-http`, but this gem does not exist in the the RubyGems repos. Is this an oversight, or is the gem not ready to be published yet?

**Comment by olleolleolle** [comment]
The gem was not yet ready, since the SSL PR (which I now merged, together with a slew of RuboCop _things_) wasn't merged.

But, now that is merged.

Are you a Faraday + HTTP.rb user? Would you be interested in maintaining this adapter gem?

**Comment by olleolleolle** [comment]
@dnd We're making progress. #16 is an up-to-date view of where the process is.

**Comment by iMacTia** [comment]
@dnd the first official release just landed on Rubygems 🎉
https://rubygems.org/gems/faraday-http

**Comment by dnd** [comment]
@olleolleolle @iMacTia thanks for the updates, and getting this published. Regarding the ask about maintaining this gem, I don't know that I have enough experience with httprb, or in depth experience with Faraday to be a good fit for the role. I also am fairly limited on time at present unfortunately. 

If that situation changes I will circle back with you guys. Thanks for working so fast to get this published!
