### ISSUE TITLE
Support Faraday 2.0

### ISSUE THREAD

**Issue by v-kumar** [lostisland/faraday-http#31]
This adapter still does  not support upgrades to Faraday 2.0.

**Comment by iMacTia** [comment]
@v-kumar the Faraday core team does not actively maintain all faraday adapters/middleware, so we very much welcome a PR to make this adapter compatible with Faraday 2.0 🙌

**Comment by igorvish** [comment]
3 points of decentralization: faraday, faraday-community adapters, http-client providers.

RIP Faraday.

**Comment by iMacTia** [comment]
Sounds like Faraday is Web 3 ready 😂!

> RIP Faraday

And yet it's the 16th most downloaded gem on Rubygems and recently passed the 500M downloads 🤔

As I mentioned above, if you rely on this adapter and need it updated for Faraday 2.0, you're very much welcome to submit a PR for that; though I wouldn't hold my breath considering your OSS contributions history 🤷

**Comment by iMacTia** [comment]
@v-kumar great news, thanks to @aka-nez we now have a [v2.0.0](https://github.com/lostisland/faraday-http/releases/tag/v2.0.0) of this gem that supports Faraday 2 and the new streaming  API 🙌 
It should already be available in Rubygems 👍 

Also cc @igorvish if you're still using Faraday 🙃

**Comment by v-kumar** [comment]
Thank you @aka-nez @iMacTia.
